### ISSUE TITLE
Allow more general count display options

### ISSUE THREAD

**Issue by leoccyao** [isaaclyman/novel-word-count-obsidian#15]
**Problem**

So first I wanted word counts. The plugin comes with word counts by default, great!
Then I wanted short descriptions. That was a quick toggle in plugin settings, amazing!
Then I wanted character counts as well. There's an option for "Pages | Words" and "Pages | Words | Characters", but information about pages isn't particularly relevant for me (I'm not ~~yet~~ a novelist myself). Looks for any other configuration options...
Sadly, nothing available.

So I went into `main.js`, found the definition of the specific description I was using, and patched it to my desired format.

**Idea**

Allow for the user to specify a custom format for counts, with substitutions of count variables, such as "{words} words, {characters} characters". Keeping presets or selectable default formats might be good, though there could be fewer of them if we allow custom formats (kept more as examples of how to write formats).

Short of that, I could PR a preset, but this could quickly become unmaintainable (and lead to a large amount of code repetition) if everyone starts contributing their own presets.

**Comment by isaaclyman** [comment]
This is good feedback. I'm very reluctant to implement custom format strings because non-programmers seriously struggle with concepts that programmers take for granted, such as matching bracket pairs and allowed/disallowed characters in an interpolated context.

One thing I could do instead is add two more dropdowns and let the user create a custom format by choosing one, two, or three data types at once. They would be displayed with a `|` between them.

So in your case, you would choose "Word Count" as the first data element, "Character Count" as the second, "None" as the third. Then in your file explorer you'd see e.g. `1,000w | 5,874ch`.

This does raise the question of what do with hotkeys...right now there's a hotkey binding for each data display option. But maybe I'll just have those point to the first data element and if you want to do more advanced configuration, you'll have to open Settings.

**Comment by isaaclyman** [comment]
Fixed in v2.8.0.
