### ISSUE TITLE
FR: Hidden note count for notes

### ISSUE THREAD

**Issue by Cammagno** [isaaclyman/novel-word-count-obsidian#16]
When the note count is selected, the counter for Notes (that always says "1 note") should be hidden.
Optionally maybe? But I see no case in which it may be useful to have it shown

**Comment by isaaclyman** [comment]
Sure, it seems unnecessary to say "1 note" on a note. But there are a few reasons why changing that is a bad idea.

- People will file issues saying "note count doesn't work" because they don't have any folders in their vault so they don't see anything.
- Then someone will file an issue saying "add a setting to let us choose whether we want to see _1 note _ or not." And that's the least useful setting I can possibly imagine.
- If you have multiple count types selected, hiding note count will mess up the alignment of statistics between files and folders.
- It creates a "special case" for note count which increases the burden of testing and maintenance on the plugin.

Saying "1 note" doesn't hurt anybody, and removing it doesn't make the plugin more useful. And since I'm not getting paid for any of this...feel free to fork the plugin.

**Comment by ryanwwest** [comment]
> People will file issues saying "note count doesn't work" because they don't have any folders in their vault so they don't see anything.
> Then someone will file an issue saying "add a setting to let us choose whether we want to see 1 note or not." And that's the least useful setting I can possibly imagine.

I feel like it would be simple to have an extra sentence of description in the plugin settings that alerts that user that when the note count option is selected, it appears for notes but not folders. Perhaps some people will still get confused, but I think it is fairly obvious and don't see a high likelihood of someone wanting a setting to see the "1 note" info on individual notes.

Notes and directories are in different categories so having different treatment for each makes sense to me.

**Comment by isaaclyman** [comment]
Update: In version 2.11.0, you can use the "Note count (folders only)" count option.

I've left the regular "Note count" available to prevent misunderstandings and for people who want to maintain alignment.

**Comment by ryanwwest** [comment]
Thanks so much!

**Comment by ryanwwest** [comment]
Just wondering @isaaclyman, do you have any interest in eventually expanding this plugin to work for counting words in the main note with selections (like https://github.com/lukeleppan/better-word-count)? If not, I totally understand as perhaps this plugin is designed only for the side panel. But that plugin doesn't work very well with Live Preview yet so I was wondering what the roadmap forward is here.

**Comment by isaaclyman** [comment]
@ryanwwest No, I don't have the time or the interest. It would be a major expansion of this plugin (actually counting the words is only 10 or so lines of code, everything else would be new code). To me it makes more sense to have that feature as a separate plugin.

I'd recommend contributing to the other plugin or writing a new one.

**Comment by ryanwwest** [comment]
Thanks for the clarification!
