### ISSUE TITLE
Large text overflow

### ISSUE THREAD

**Issue by Catalyst-42** [isaaclyman/novel-word-count-obsidian#48]
**Description**
Hi, I'm using an extension to display the first alias below the page. And if the alias is too big, it moves outside its block.

![Overflow](https://github.com/isaaclyman/novel-word-count-obsidian/assets/72890979/27dff370-c197-47a7-8617-8c42fc6a7cfe)

Also if I display the alignment not `below` the page, but `inline`, then it starts replacing the page title with dots.

![OverflowDirection](https://github.com/isaaclyman/novel-word-count-obsidian/assets/72890979/a56ab10c-34e7-4b7c-8a49-24083a59a856)

I think this is wrong, because aliases are less important than the name of the page, it would be better to have the alias itself replaced by dots and not go horizontally out of bounds.

Then the "right" view for me would look something like this:

![Снимок экрана 2023-08-13 в 22 10 30](https://github.com/isaaclyman/novel-word-count-obsidian/assets/72890979/789a3b65-83a1-457f-b0d4-14e4788864fb)

![Снимок экрана 2023-08-13 в 22 20 50](https://github.com/isaaclyman/novel-word-count-obsidian/assets/72890979/fa86870b-2e4a-491a-92a6-4b1f6933eae8)

**Device**
Occurs on Obsidian v1.3.7, MacOs, also same thing on iOS

**Comment by isaaclyman** [comment]
Fixed in v2.21.2, with caveats.

"Below" counts will ellipsize when they exceed the available space. However, it's not reasonable to truncate "Inline" and "Right-aligned" counts instead of the note title when there isn't enough space for both. Otherwise, the plugin would be useless for notes with very long titles. I believe most users would consider the note title (which can be seen in the note itself) to be less essential than the plugin counts (which cannot be seen anywhere else).

I have added some code to ensure that the note title can never be _completely_ hidden by a long alias.
