### ISSUE TITLE
Make Word counts on files right-aligned, as they already are on folders

### ISSUE THREAD

**Issue by Gewerd-Strauss** [isaaclyman/novel-word-count-obsidian#6]
Hello,

might it be possible to right-align the wordcount on the files themselves like they are on folders as well? 
I believe it would make spotting it easier because they are all at a uniform position, instead of fuzzying up the file names themselves. Especially on a lot of files with different length names this can become irritating to jump around.

![grafik](https://user-images.githubusercontent.com/80548781/171820595-8c1b4a13-c7d6-4ef1-9b55-985dc7924512.png)
![grafik](https://user-images.githubusercontent.com/80548781/171820745-95dc3f16-dbb0-4506-9fe4-454aeff1ee8f.png)

---
SIncerely,  
~Gw

**Comment by isaaclyman** [comment]
Word counts aren't supposed to be right-aligned on folders -- that's probably the result of a style conflict with a different plugin. I don't think it's a good idea to right-align all the counts, since folder/file names can extend beyond the right edge of the pane and that would result in all the counts being hidden.

**Comment by isaaclyman** [comment]
@Gewerd-Strauss I decided to add this as a setting. If you update to release 2.5.0, you can choose in the plugin settings whether data is inline, right-aligned, or below each file/folder name.

@eleanorkonik you may also find this useful for your super long file names.

**Comment by Gewerd-Strauss** [comment]
That's neat, and exactly what I was looking for. Thank you very much :)
