### ISSUE TITLE
Read Time value in sidebar

### ISSUE THREAD

**Issue by redactedscribe** [isaaclyman/novel-word-count-obsidian#61]
**Problem**

I want to know the time taken to read a document.

**Idea**

A read time value for each file in the sidebar. From what I've read, the typical reading speed is 200-300 words per minute. [A plugin for VS Code](https://github.com/johnpapa/vscode-read-time) sets the default reading speed to `200` to calculate reading time for a document. It would be great if this value was customisable, just like the "Words per page" value is. The displayed value could use `s`, `m`, `h` suffixes: `48s`, `5m`, `1h 23m`.

Thanks!

**Comment by isaaclyman** [comment]
I've been waiting for someone to request this. Won't take long to implement.

Due to space constraints, I'll like go with a single measure for each note, e.g.:

'10s read' (anything from 1 second up to 1 minute)

'10m read' (from 1 minute up to 180 minutes)

'10h read' (3 hours and up)

With a digit of precision after the decimal.

**Comment by isaaclyman** [comment]
Right, if abbreviations are toggled on it would just be `10.2h` or whatever.

You make a good point, `5h32m` is still more compact than some of the other count types...I'll give that some more thought.

**Comment by redactedscribe** [comment]
Thanks for making it happen! If I encounter any issues, I'll let you know.
