### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by GanymedeWordsmyth** [isaaclyman/novel-word-count-obsidian#85]
**Problem**

Currently the date format is YYYY/MM/DD, not the biggest issue, but I'd like to be able to customize this.

**Idea**

A way to customize this under the settings somewhere. Maybe under the advanced options section.

**Comment by isaaclyman** [comment]
This is unnecessary IMO. The current date format is unambiguous in every locale, and since there's no way to accurately detect the user's current locale, this is the only reasonable standard.

I understand the urge to tinker but it's not worth the added complexity and maintenance burden. If more users request it, I'll revisit.
