### ISSUE TITLE
Words count disappear on workspace load

### ISSUE THREAD

**Issue by MalignantCarp** [isaaclyman/novel-word-count-obsidian#9]
**Description**

When you load a workspace, the word counts disappear and don't get reloaded until a change is made to a file. At that point, it just updates the one folder affected by the file. There could be a workspace event that might allow for a fix.

![image](https://user-images.githubusercontent.com/93364935/176950072-b8e29ea9-b009-49ba-acb9-fd75ebb0b5cb.png)

**Device**

Tested on Windows and Manjaro Linux

**Comment by isaaclyman** [comment]
Hi @MalignantCarp, does this happen when you start Obsidian in Safe Mode? It's probably a conflict with another plugin, since I'm not able to reproduce that issue on my install.

As a workaround, there's a button in the plugin settings that recounts the entire vault and you can bind it to a hotkey for convenience.

If you're able to determine which other plugin is causing the conflict I may be able to look into this further. It also may help to turn on Debug Mode in the plugin settings, close and reopen the workspace, open the developer console, and post the output here.

**Comment by MalignantCarp** [comment]
(Preface: Not sure what you mean by Safe Mode. If it is what I think, that would disable this plugin as well.)

So in both version 0.15.3 on Windows 10 and 0.14.15 on Manjaro Linux, with no other community plugins enabled on a clean execution of Obsidian, when I load a saved workspace using Manage Workspaces (from Ctrl+P menu) (this is Manage Workspace Layouts in 0.15.3), the word counts disappear. There is no output from the debug mode at this point. I've added some comments before and after I loaded a workspace for illustration:

![image](https://user-images.githubusercontent.com/93364935/176969847-25a0f802-6be5-4bd3-a50a-c1420b020a82.png)

Then when I reanalyze, it fills in the word counts. Debug output:

![image](https://user-images.githubusercontent.com/93364935/176969886-3e8c4f61-016e-432e-99a4-eed3bfae8f41.png)

Also tested with a brand new vault in 0.15.3 with just Novel Word Count installed and the Core > Workspaces plugin. Same result.

**Comment by isaaclyman** [comment]
Very helpful, thank you. I was confusing _workspaces_ with _vaults_ since I’d never heard of the former (sorry, Obsidian newbie here).

It’s a long weekend here, I should be able to take some time next week to familiarize myself with workspaces and figure out if there’s something in the API that lets me hook into workspace change events. Stay tuned.

**Comment by MalignantCarp** [comment]
No worries, no worries. Welcome to the community. :)

Since the plugin I'm currently working on was already plugged into some workspace events, I looked at some options. It would appear both `layout-change` and `active-leaf-change` are triggered by the Workspace change. Not ideal for certain, as both are triggered in multiple situations. `layout-change` is probably your best bet.

I kind of wish there were a separate event for changes in workspace, but either of these should at least give you the opportunity to re-inject the word counts.

**Comment by isaaclyman** [comment]
All right, I was able to reproduce the issue and hooking into `layout-change` was a very easy fix. Thanks for the help @MalignantCarp. Release 2.5.1 is available now.
